version: '3.6'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    stdin_open: true
    environment:
      - REACT_APP_BACKEND_HOST=localhost
      - SKIP_PREFLIGHT_CHECK=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5003:5003
    expose:
      - 5003
    volumes:
      - ./backend:/app

  mssql_db:
    container_name: mssql_db
    image: mcr.microsoft.com/mssql/server
    expose:
      - 1433
    environment:
      - SA_PASSWORD=photos@123
      - ACCEPT_EULA=Y